import type { PracticeArea } from '@/types'

export const practiceAreas: PracticeArea[] = [
  {
    slug: 'car-accidents',
    title: 'Car Accident Lawyers',
    shortTitle: 'Car Accidents',
    icon: 'Car',
    description: 'Aggressive representation for victims of car accidents throughout California, Texas, and North Carolina.',
    heroHeadline: 'Injured in a Car Accident? Fight for Every Dollar You Deserve.',
    heroSubheadline: 'Insurance companies will try to minimize your claim. We won\'t let them. Our car accident attorneys have recovered millions for clients just like you — with no fees unless we win.',
    metaTitle: 'Car Accident Lawyer | Accident Pros | CA, TX, NC',
    metaDescription: 'Injured in a car accident? Our attorneys fight for maximum compensation in California, Texas, and North Carolina. Free consultation. No fees unless we win.',
    relatedAreas: ['truck-accidents', 'rideshare-accidents', 'motorcycle-accidents'],
  },
  {
    slug: 'truck-accidents',
    title: 'Truck Accident Lawyers',
    shortTitle: 'Truck Accidents',
    icon: 'Truck',
    description: 'Complex truck accident claims require specialized knowledge. We handle the full legal burden so you can heal.',
    heroHeadline: 'Truck Accident Victim? The Insurance Companies Have Lawyers. So Should You.',
    heroSubheadline: 'Commercial trucking accidents cause devastating injuries. Trucking companies and their insurers act fast to limit liability. We act faster — and we fight harder.',
    metaTitle: 'Truck Accident Lawyer | Accident Pros | CA, TX, NC',
    metaDescription: 'Truck accident victim? Our attorneys handle complex commercial trucking cases in California, Texas, and North Carolina. Free consultation. No fees unless we win.',
    relatedAreas: ['car-accidents', 'commercial-vehicle-accidents', 'wrongful-death'],
  },
  {
    slug: 'motorcycle-accidents',
    title: 'Motorcycle Accident Lawyers',
    shortTitle: 'Motorcycle Accidents',
    icon: 'Bike',
    description: 'Motorcycle riders face serious bias from insurers. We counter that bias with facts, evidence, and aggressive advocacy.',
    heroHeadline: 'Motorcycle Accident? Don\'t Let Bias Cost You Your Recovery.',
    heroSubheadline: 'Motorcyclists are often blamed even when they\'re not at fault. Our attorneys know how to build an airtight case — and how to fight back against insurance bias.',
    metaTitle: 'Motorcycle Accident Lawyer | Accident Pros | CA, TX, NC',
    metaDescription: 'Injured in a motorcycle accident? We fight insurer bias and recover full compensation for CA, TX, and NC riders. Free consultation. No fees unless we win.',
    relatedAreas: ['car-accidents', 'traumatic-brain-injury', 'wrongful-death'],
  },
  {
    slug: 'rideshare-accidents',
    title: 'Rideshare Accident Lawyers',
    shortTitle: 'Rideshare Accidents',
    icon: 'Smartphone',
    description: 'Uber, Lyft, and other rideshare accidents involve complex insurance layers. We untangle them so you get paid.',
    heroHeadline: 'Injured in an Uber or Lyft? Multiple Insurers. One Attorney Team.',
    heroSubheadline: 'Rideshare accidents are legally complex. Whose insurance applies depends on exactly when the accident happened. We know how to navigate every layer — and we won\'t stop until you\'re made whole.',
    metaTitle: 'Rideshare Accident Lawyer (Uber & Lyft) | Accident Pros | CA, TX, NC',
    metaDescription: 'Injured in an Uber or Lyft accident? Our rideshare accident attorneys handle the complex insurance landscape. Free consultation. No fees unless we win.',
    relatedAreas: ['car-accidents', 'delivery-driver-accidents'],
  },
  {
    slug: 'pedestrian-accidents',
    title: 'Pedestrian Accident Lawyers',
    shortTitle: 'Pedestrian Accidents',
    icon: 'PersonStanding',
    description: 'When a vehicle strikes a pedestrian, the injuries are almost always severe. We fight to ensure you receive full compensation.',
    heroHeadline: 'Hit as a Pedestrian? The Injuries Are Serious. The Fight Should Be Too.',
    heroSubheadline: 'Pedestrians are among the most vulnerable road users. When a vehicle strikes you, the damage can be catastrophic. Our attorneys pursue every dollar of compensation you\'re owed.',
    metaTitle: 'Pedestrian Accident Lawyer | Accident Pros | CA, TX, NC',
    metaDescription: 'Struck as a pedestrian? Our attorneys fight for maximum compensation for serious injuries in California, Texas, and North Carolina. Free consultation. No fees unless we win.',
    relatedAreas: ['car-accidents', 'wrongful-death', 'traumatic-brain-injury'],
  },
  {
    slug: 'slip-and-fall',
    title: 'Slip and Fall Lawyers',
    shortTitle: 'Slip & Fall',
    icon: 'AlertTriangle',
    description: 'Property owners have a duty to keep their premises safe. When they fail, we hold them accountable.',
    heroHeadline: 'Slipped and Fallen on Someone Else\'s Property? We\'ll Make Them Accountable.',
    heroSubheadline: 'Property owners and businesses are legally responsible for maintaining safe conditions. If a dangerous floor, poor lighting, or neglected hazard caused your fall, you may be entitled to significant compensation.',
    metaTitle: 'Slip and Fall Lawyer | Accident Pros | CA, TX, NC',
    metaDescription: 'Injured in a slip and fall? Our premises liability attorneys hold property owners accountable in California, Texas, and North Carolina. Free consultation. No fees unless we win.',
    relatedAreas: ['premises-liability', 'dog-bites'],
  },
  {
    slug: 'premises-liability',
    title: 'Premises Liability Lawyers',
    shortTitle: 'Premises Liability',
    icon: 'Building2',
    description: 'Injuries on someone else\'s property — whether a store, apartment, or commercial space — may entitle you to compensation.',
    heroHeadline: 'Injured on Someone Else\'s Property? You Have Rights.',
    heroSubheadline: 'Businesses, landlords, and property owners are legally required to maintain safe conditions for visitors. When they fail and you\'re injured, our attorneys pursue the full compensation you deserve.',
    metaTitle: 'Premises Liability Lawyer | Accident Pros | CA, TX, NC',
    metaDescription: 'Injured on someone else\'s property? Our premises liability attorneys fight for compensation in California, Texas, and North Carolina. No fees unless we win.',
    relatedAreas: ['slip-and-fall', 'construction-accidents'],
  },
  {
    slug: 'wrongful-death',
    title: 'Wrongful Death Lawyers',
    shortTitle: 'Wrongful Death',
    icon: 'Heart',
    description: 'Losing a loved one due to someone else\'s negligence is devastating. We fight to ensure your family receives justice and financial security.',
    heroHeadline: 'Lost a Loved One Due to Negligence? We\'ll Fight for Justice.',
    heroSubheadline: 'A wrongful death claim can never replace what you\'ve lost — but it can secure your family\'s financial future and hold the responsible party accountable. We handle every aspect of your case with compassion and resolve.',
    metaTitle: 'Wrongful Death Lawyer | Accident Pros | CA, TX, NC',
    metaDescription: 'Lost a loved one to negligence? Our wrongful death attorneys compassionately fight for your family\'s justice and financial security. Free consultation. No fees unless we win.',
    relatedAreas: ['car-accidents', 'truck-accidents', 'traumatic-brain-injury'],
  },
  {
    slug: 'traumatic-brain-injury',
    title: 'Traumatic Brain Injury Lawyers',
    shortTitle: 'Brain Injury',
    icon: 'Brain',
    description: 'TBI cases require specialized medical and legal knowledge. Our attorneys partner with leading experts to build the strongest possible case.',
    heroHeadline: 'Suffered a Brain Injury? The Long-Term Impact Demands Maximum Compensation.',
    heroSubheadline: 'Traumatic brain injuries can affect every aspect of your life — work, relationships, independence. We work with leading medical experts to document your full damages and fight for every dollar you\'ll need for the road ahead.',
    metaTitle: 'Traumatic Brain Injury Lawyer | Accident Pros | CA, TX, NC',
    metaDescription: 'Suffered a TBI? Our attorneys work with medical experts to maximize your brain injury compensation in California, Texas, and North Carolina. Free consultation. No fees unless we win.',
    relatedAreas: ['car-accidents', 'truck-accidents', 'wrongful-death'],
  },
  {
    slug: 'dog-bites',
    title: 'Dog Bite Lawyers',
    shortTitle: 'Dog Bites',
    icon: 'Shield',
    description: 'Dog bite injuries can be physically and emotionally traumatic. We pursue full compensation from negligent pet owners and their insurers.',
    heroHeadline: 'Bitten by a Dog? The Owner May Owe You More Than You Think.',
    heroSubheadline: 'California, Texas, and North Carolina each have laws that hold dog owners strictly liable for bites. Our attorneys know how to pursue full compensation for medical costs, scarring, and emotional trauma.',
    metaTitle: 'Dog Bite Lawyer | Accident Pros | CA, TX, NC',
    metaDescription: 'Bitten by a dog? Our attorneys pursue full compensation for injuries, scarring, and trauma under CA, TX, and NC dog bite laws. Free consultation. No fees unless we win.',
    relatedAreas: ['premises-liability', 'slip-and-fall'],
  },
  {
    slug: 'products-liability',
    title: 'Products Liability Lawyers',
    shortTitle: 'Products Liability',
    icon: 'Package',
    description: 'Defective products can cause catastrophic harm. We hold manufacturers, distributors, and retailers accountable.',
    heroHeadline: 'Hurt by a Defective Product? The Manufacturer May Owe You Compensation.',
    heroSubheadline: 'Defective design, manufacturing errors, and inadequate warnings cause serious injuries every day. Accident Pros has the resources and expertise to take on large manufacturers and recover what you\'re owed.',
    metaTitle: 'Products Liability Lawyer | Accident Pros | CA, TX, NC',
    metaDescription: 'Injured by a defective product? Our products liability attorneys hold manufacturers accountable in California, Texas, and North Carolina. Free consultation. No fees unless we win.',
    relatedAreas: ['construction-accidents', 'wrongful-death'],
  },
  {
    slug: 'construction-accidents',
    title: 'Construction Accident Lawyers',
    shortTitle: 'Construction Accidents',
    icon: 'HardHat',
    description: 'Construction site injuries are among the most severe. We navigate the complex web of liability to maximize your recovery.',
    heroHeadline: 'Injured on a Construction Site? Multiple Parties May Be Liable.',
    heroSubheadline: 'Construction accidents can involve contractors, subcontractors, property owners, and equipment manufacturers. Our attorneys identify every responsible party and pursue each one to maximize your total recovery.',
    metaTitle: 'Construction Accident Lawyer | Accident Pros | CA, TX, NC',
    metaDescription: 'Injured on a construction site? Our attorneys pursue all liable parties for maximum compensation in California, Texas, and North Carolina. Free consultation. No fees unless we win.',
    relatedAreas: ['products-liability', 'premises-liability', 'wrongful-death'],
  },
  {
    slug: 'commercial-vehicle-accidents',
    title: 'Commercial Vehicle Accident Lawyers',
    shortTitle: 'Commercial Vehicles',
    icon: 'Truck',
    description: 'Accidents with delivery vans, company cars, and other commercial vehicles often involve employer liability.',
    heroHeadline: 'Hit by a Company Vehicle? The Employer May Bear Responsibility.',
    heroSubheadline: 'When an employee causes an accident while on the job, their employer can be held liable. Commercial vehicle cases often involve higher insurance limits and greater recovery potential.',
    metaTitle: 'Commercial Vehicle Accident Lawyer | Accident Pros | CA, TX, NC',
    metaDescription: 'Injured by a commercial vehicle? Our attorneys pursue employer liability for maximum compensation in California, Texas, and North Carolina. Free consultation. No fees unless we win.',
    relatedAreas: ['truck-accidents', 'delivery-driver-accidents'],
  },
  {
    slug: 'aviation-accidents',
    title: 'Aviation Accident Lawyers',
    shortTitle: 'Aviation Accidents',
    icon: 'Plane',
    description: 'Aviation accident cases involve complex federal regulations and high stakes. We have the resources to handle them.',
    heroHeadline: 'Injured in an Aviation Accident? Federal Law May Entitle You to Significant Compensation.',
    heroSubheadline: 'Aviation accidents — whether commercial airline, charter, or private aircraft — are subject to complex federal regulations. Our attorneys have the resources and expertise to pursue maximum recovery from airlines, manufacturers, and operators.',
    metaTitle: 'Aviation Accident Lawyer | Accident Pros | CA, TX, NC',
    metaDescription: 'Injured in an aviation accident? Our attorneys handle complex airline and aircraft injury claims in California, Texas, and North Carolina. Free consultation. No fees unless we win.',
    relatedAreas: ['products-liability', 'wrongful-death'],
  },
  {
    slug: 'delivery-driver-accidents',
    title: 'Delivery Driver Accident Lawyers',
    shortTitle: 'Delivery Drivers',
    icon: 'PackageOpen',
    description: 'Injured by an Amazon, FedEx, UPS, or DoorDash driver? These cases involve complex insurance and employment questions.',
    heroHeadline: 'Injured by a Delivery Driver? Don\'t Accept Less Than You\'re Owed.',
    heroSubheadline: 'Accidents involving delivery drivers for Amazon, FedEx, UPS, DoorDash, and others often involve multiple layers of insurance and employment classification questions. We cut through the complexity to get you paid.',
    metaTitle: 'Delivery Driver Accident Lawyer | Accident Pros | CA, TX, NC',
    metaDescription: 'Injured by a delivery driver (Amazon, FedEx, UPS, DoorDash)? Our attorneys handle the complex liability questions. Free consultation. No fees unless we win.',
    relatedAreas: ['rideshare-accidents', 'commercial-vehicle-accidents'],
  },
  {
    slug: 'sexual-assault',
    title: 'Sexual Assault & Battery Lawyers',
    shortTitle: 'Sexual Assault',
    icon: 'ShieldCheck',
    description: 'Survivors of sexual assault may have civil claims against individuals and the institutions that failed to protect them.',
    heroHeadline: 'Sexual Assault Survivors: Civil Justice Can Be Yours.',
    heroSubheadline: 'Beyond the criminal justice system, survivors of sexual assault and battery may have powerful civil claims against perpetrators and the institutions — schools, employers, businesses — that enabled or failed to prevent the harm. We handle these cases with absolute confidentiality and compassion.',
    metaTitle: 'Sexual Assault Civil Lawyer | Accident Pros | CA, TX, NC',
    metaDescription: 'Sexual assault survivors may have civil claims. Our attorneys handle these cases with confidentiality and compassion in California, Texas, and North Carolina. Free consultation.',
    relatedAreas: ['premises-liability', 'wrongful-death'],
  },
]

export const featuredPracticeAreas = practiceAreas.slice(0, 8)
